"""Публичный API модуля src.ast.

Импортируйте что угодно напрямую из src.ast:

    from src.ast import Node, SelectStmt, Dialect, Translator
"""
from .metadata import (
    Annotation,
    AnnotationRecord,
    CommentKind,
    CommentPlacement,
    Dialect,
    Kind,
    Position,
    SourceComment,
    Span,
)
from .registry import (
    Rule,
    TranslateContext,
    Translator,
    default_translator,
)
from .node import Node
from .nodes import (
    # Абстрактные базы
    Expression,
    FromItem,
    Statement,
    # Выражения
    ArrayConstructor,
    BetweenExpr,
    BinaryOp,
    LikeExpr,
    SimilarToExpr,
    Cast,
    CaseExpr,
    ColumnRef,
    FunctionCall,
    Identifier,
    Literal,
    ParamRef,
    StarExpr,
    SubqueryExpr,
    TupleConstructor,
    TypeRef,
    UnaryOp,
    WhenBranch,
    # Клаузы SELECT
    CommonTableExpr,
    DistinctClause,
    FetchClause,
    FrameBound,
    FrameSpec,
    GroupByClause,
    LockingClause,
    OrderByItem,
    SampleClause,
    SetOpClause,
    WindowDef,
    WindowSpec,
    WithClause,
    WithFillSpec,
    # FROM-элементы
    JoinExpr,
    SubqueryRef,
    TableFunctionRef,
    TableRef,
    # DDL
    ColumnConstraint,
    ColumnDef,
    EngineSpec,
    ExcludeElement,
    LikeClause,
    OnConflictClause,
    SettingAssignment,
    TableConstraint,
    TtlClause,
    TtlRule,
    # Операторы
    AlterRoleStmt,
    BeginStmt,
    CommitStmt,
    CopyStmt,
    CreateDatabaseStmt,
    CreateFunctionStmt,
    CreateIndexStmt,
    CreateRoleStmt,
    CreateTableStmt,
    CreateUserStmt,
    CreateViewStmt,
    DefaultValues,
    FunctionArg,
    GrantStmt,
    IndexColumn,
    InsertSource,
    InsertStmt,
    LockTableStmt,
    MergeStmt,
    PrepareTransactionStmt,
    RawStatement,
    RollbackStmt,
    SavepointStmt,
    SelectStmt,
    SetConstraintsStmt,
    SetTransactionStmt,
    SelectTarget,
    ValuesClause,
    # Корень
    Script,
)

__all__ = [
    # metadata
    "Annotation",
    "AnnotationRecord",
    "CommentKind",
    "CommentPlacement",
    "Dialect",
    "Kind",
    "Position",
    "SourceComment",
    "Span",
    # registry
    "Rule",
    "TranslateContext",
    "Translator",
    "default_translator",
    # node
    "Node",
    # nodes — абстрактные базы
    "Expression",
    "FromItem",
    "Statement",
    # nodes — выражения
    "ArrayConstructor",
    "BetweenExpr",
    "BinaryOp",
    "LikeExpr",
    "SimilarToExpr",
    "Cast",
    "CaseExpr",
    "ColumnRef",
    "FunctionCall",
    "Identifier",
    "Literal",
    "ParamRef",
    "StarExpr",
    "SubqueryExpr",
    "TupleConstructor",
    "TypeRef",
    "UnaryOp",
    "WhenBranch",
    # nodes — клаузы SELECT
    "CommonTableExpr",
    "DistinctClause",
    "FetchClause",
    "FrameBound",
    "FrameSpec",
    "GroupByClause",
    "LockingClause",
    "OrderByItem",
    "SampleClause",
    "SetOpClause",
    "WindowDef",
    "WindowSpec",
    "WithClause",
    "WithFillSpec",
    # nodes — FROM
    "JoinExpr",
    "SubqueryRef",
    "TableFunctionRef",
    "TableRef",
    # nodes — DDL
    "ColumnConstraint",
    "ColumnDef",
    "EngineSpec",
    "ExcludeElement",
    "LikeClause",
    "OnConflictClause",
    "SettingAssignment",
    "TableConstraint",
    "TtlClause",
    "TtlRule",
    # nodes — операторы
    "AlterRoleStmt",
    "BeginStmt",
    "CommitStmt",
    "CopyStmt",
    "CreateDatabaseStmt",
    "CreateFunctionStmt",
    "CreateIndexStmt",
    "CreateRoleStmt",
    "CreateTableStmt",
    "CreateUserStmt",
    "CreateViewStmt",
    "DefaultValues",
    "FunctionArg",
    "GrantStmt",
    "IndexColumn",
    "InsertSource",
    "InsertStmt",
    "LockTableStmt",
    "MergeStmt",
    "PrepareTransactionStmt",
    "RawStatement",
    "RollbackStmt",
    "SavepointStmt",
    "SelectStmt",
    "SelectTarget",
    "SetConstraintsStmt",
    "SetTransactionStmt",
    "ValuesClause",
    # nodes — корень
    "Script",
]
